### ISSUE TITLE
Outer element can't slot child into inner custom element

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/shadydom#116]
_From @JanMiksovsky on March 22, 2017 21:25_

See https://jsbin.com/nehuta/edit?html,output, in which an extremely simple composition of web components fails to render.

The crux of it is that an outer custom element with a slot inside an inner custom element doesn't have its light DOM children appear inside the inner element as expected. If a custom `outer-element` has the following template:

    <template id="outerTemplate">
      <inner-element>
        <slot></slot>
      </inner-element>
    </template>

then

    <outer-element>Hello</outer-element>

shows nothing. The jsbin works in native Shadow DOM in both Blink and WebKit.

The existing of the custom `inner-element` is related to triggering the issue. If that custom element is replaced with a standard HTML element, the `slot` works as expected.

_Copied from original issue: webcomponents/webcomponentsjs#747_

**Comment by notwaldorf** [comment]
This sounds like a Shadow DOM bug, moving it there.

**Comment by Saulis** [comment]
If it helps debugging the issue, here's a similar setup done using Polymer 2 – where Shady DOM seems to me working as it should: https://jsfiddle.net/Saulis/1jLepepq/

**Comment by sorvell** [comment]
This looks like a timing issue that we'll definitely want to fix.

**Comment by sorvell** [comment]
Currently adding dom to a shadowRoot of the following form is not supported.

```
<host>
  <slot></slot>
  shadowRoot (that has not yet rendered)
    <slot></slot>
...
someElement.shadowRoot.appendChild(host)
```

This is an incorrect optimization and we'll need to be more careful about checking if a shadowRoot has an insertion point.
