### ISSUE TITLE
Focusing a shadow child doesn't bubble up to the parent

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/shadydom#124]
Open the console in these examples, and press the `focus child` button:
- In Shady DOM, the parent doesn’t get that focus event: http://output.jsbin.com/coheniv?wc-shadydom=true&wc-ce=true
- In Shadow DOM it does: http://output.jsbin.com/coheniv

/cc @azakus

**Comment by azakus** [comment]
Oops, `focus` and `blur` events weren't being marked as "composed", which broke a whole bunch of stuff 😭

**Comment by notwaldorf** [comment]
I updated the jsbin with the latest release, but it still doesn't work? http://output.jsbin.com/jifokun?wc-shadydom=true&wc-ce=true :(

**Comment by notwaldorf** [comment]
Ignore me, a new RC hasn't been tagged
