### ISSUE TITLE
It seems that once a shadow child is focused, the host can't be blurred

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/shadydom#126]
Setup: A custom element with an input inside it. When the host receives a `focus` event, it focuses the child. If you imperatively call `blur` on the host (which is the `document.activeElement`, I checked`), it doesn't actually call the `blur` handler anymore :(

Click the button i the demo. It will call `focus()`, and one second later, call `blur()`:

- Shady DOM (does not get blurred): http://output.jsbin.com/wapulap?wc-shadydom=true&wc-ce=true
- Shadow DOM (gets blurred): http://output.jsbin.com/wapulap

cc @azakus

**Comment by azakus** [comment]
Ugh, this might actually be because the native methods know if the element is focused, and technically the host isn't focused anymore.

We might have to patch the native methods to make this work.
