### ISSUE TITLE
shadowRoot.contains not working

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#137]
`el.shadowRoot.contains()` doesn't work as expected when using ShadyDOM

```html
  <div id="host"></div>
  <script>
    host.attachShadow({mode: 'open'});
    var a = document.createElement('a');
    host.shadowRoot.appendChild(a);

    console.log(host.shadowRoot.contains(a));
  </script>
```
http://jsbin.com/rudezep/2/edit?html,console

**Comment by CaptainCodeman** [comment]
This might explain an issue I had with the IntersectionObserver polyfill combined with the WebComponents polyfill - it fails at 'contains'

**Comment by TimvdLippe** [comment]
This appears to be fixed with the latest version: http://jsbin.com/tuzutusiha/edit?html,console
