### ISSUE TITLE
attachShadow issue with Firefox 53

### ISSUE THREAD

**Issue by Slaals** [webcomponents/shadydom#144]
Hi,

Firefox doesn't seem to create any shadow root when using `attachShadow` to an element.

[See the issue](https://jsfiddle.net/tzmkaz8q/4/)

The `p` shouldn't be affected by the style in the parent's document of the shadow root. It works well on Chrome.

Note that I use the last available version of ShadyDOM on CDNjs `https://cdnjs.cloudflare.com/ajax/libs/webcomponentsjs/1.0.0-rc.11/webcomponents-sd-ce.js`

**Comment by TimvdLippe** [comment]
This is working as intended, as the polyfills can not fully implement shadow dom. If you are looking for style encapsulation, you need to use https://github.com/webcomponents/shadycss which achieves most of the behavior. However, as no native shadow dom is available, document wide CSS selectors can still pierce through. For more information check out https://github.com/webcomponents/shadycss#document-level-styling-is-not-scoped-by-default
