### ISSUE TITLE
Appending Document Fragments to Nodes Breaks Multiple Queries

### ISSUE THREAD

**Issue by ChadKillingsworth** [webcomponents/shadydom#148]
In FireFox, the following behavior is observed:

```js
const div = document.createElement('div');
document.body.appendChild(div);

const frag = document.createDocumentFragment();
frag.appendChild(document.createElement('span'));

div.appendChild(frag);

console.log(div.childNodes.length); // logs 0
console.log(div.children); // logs an empty array
console.log(document.querySelector('span')); // logs an empty array
console.log(document.getElementsByTagName('span')); // logs a node list with a span element
```

This breaks all kinds of functionality. For my project it breaks e2e tests since we use query selector to find elements when shadowDom support is not available in the browser.

This seems related to #147

**Comment by sorvell** [comment]
I'm not able to reproduce this based on the steps provided. See console output in Firefox for this jsbin: http://jsbin.com/netinu/edit?html,output

Are there any additional steps to see the problem? If possible, it'd be great if you could clone the jsbin andy modify it to show the issue. Thanks.

**Comment by ChadKillingsworth** [comment]
Upgrading to the latest (webcomponents rc11) removed this issue. Not sure what caused it or how it got fixed, but at least that's gone.

Sorry for the distraction - I should have checked against master first.
