### ISSUE TITLE
I think there's something wrong around focus

### ISSUE THREAD

**Issue by notwaldorf** [webcomponents/shadydom#15]
Suspecting in: https://github.com/webcomponents/shadydom/blob/master/src/event-mixin.js

I have a custom element `someElement`, and code that does:
```js
someElement.addEventListener('focus', function() {
  debugger
});

Polymer.Base.fire('focus', {}, {
      bubbles: false,
      node: someElement
});
```

In Canary, if I include the latest `webcomponents-lite.js`, that listener doesn't fire. If I don't include it, it fires :(

I realize I said I would write tests for this and I haven't, but here is this in the meantime

/cc @azakus

**Comment by ebidel** [comment]
Not sure if this is related: https://github.com/Polymer/polymer/issues/3929

**Comment by notwaldorf** [comment]
@ebidel That should be fixed in the latest commit
