### ISSUE TITLE
Do not produce an error when `null` is passed to `addEventListener`

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadydom#152]
The platform allows `null` to be the handler passed to `addEventListener` and does not generate any error when the event fires (e.g. `element.addEventListener('click', null)`. Shady DOM currently produces an error in this case and should not.

This is causing https://github.com/Polymer/polymer/issues/4620.

**Comment by valdrinkoshi** [comment]
This is [already handled](https://github.com/webcomponents/shadydom/blob/master/src/patch-events.js#L287) and shipped in 1.0.0
