### ISSUE TITLE
Fails to load in PhantomJS - "Attempting to configurable attribute of unconfigurable property"

### ISSUE THREAD

**Issue by mattdsteele** [webcomponents/shadydom#158]
Using PhantomJS 2.1.1. Same problem as https://github.com/webcomponents/custom-elements/issues/70.

We can get around the custom-elements issue by using a [different polyfill](https://github.com/WebReflection/document-register-element) in PhantomJS, but I'm not sure there's a good option for shadow DOM.

**Comment by treshugart** [comment]
I'm wondering if it's worth supporting PhantomJS since the [maintainer stepped down](https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE), advocating for the usage of Chrome Headless instead.

What's the goal here? Maybe it's worth trying to use a node environment with something like Undom or the SSR lib we're developing?

**Comment by mattdsteele** [comment]
We're building a set of web components (CE+SD) to be used in various contexts. One of these in AngularJS 1.x apps, which have been built over the years and run tests with Karma+PhantomJS.

Yeah, Chrome Headless is probably the direction we'll ultimately take, but it doesn't have quite the support we'd need. Many of our CI servers are running on older CentOS instances, which Chrome doesn't support (but PhantomJS works fine on). Was hoping we could continue running tests while we move off dozens of servers.

**Comment by mattdsteele** [comment]
Gonna close this and just note for posterity the supported browser list.

As you mentioned, this isn't really solvable without a change to PhantomJS. We ended up managing this with a guard that prevents shadydom from loading if you're inside Phantom; which works well enough until we can move to Chrome Headless.
