### ISSUE TITLE
Click event doesn't bubble when fired using click() function

### ISSUE THREAD

**Issue by Saulis** [webcomponents/shadydom#159]
Not fully sure if this is bug or not, but it's behavior difference between native Shadow and ShadyDOM nevertheless:

When an element inside shadow root is clicked programmatically using `click()`, the event doesn't bubble all the way to the host element in ShadyDOM although the event has `bubbles: true`.

On native Shadow, a click listener on the host element always catches clicks within the shadow root, both actual user clicks and `click()` calls.

See snippet: https://jsfiddle.net/Saulis/dw3kus6g/2/ (try clicking on the "Hello!" label directly first, and then using the button)

**Comment by DanDeMicco** [comment]
+1, running into same issue
