### ISSUE TITLE
getElementById throws DOMException when called with IDs that are not valid css selectors

### ISSUE THREAD

**Issue by filet0fish** [webcomponents/shadydom#160]
Elements with IDs that are not valid css selectors (https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier) should be found with `getElementById` but result in DOMException (code 12).  The polyfill is prepending a `#` but needs to also escape characters not in `[A-Za-z0-9\-_]`.

```html
<div id="valid/html5/id"></div>
```

```javascript
document.getElementById('valid/html5/id'); // Works without polyfill, Throws exception with polyfill
document.querySelector('#valid/html5/id'); // Throws exception with and without
document.querySelector('#valid\\/html5\\/id'); // Works with and without polyfill
```

**Comment by micschro** [comment]
We are experiencing this problem when using the polyfill along with the google api, which uses iframe ids that are not valid css selectors when unescaped: 
```javascript
document.querySelector('#apiproxy123hash123.1234567')
```
should be escaped to 
```javascript
document.querySelector('#apiproxy123hash123\\.1234567')
```
So
```javascript
document.getElementById('apiproxy123hash123.1234567')
```
works with or without polyfill.

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadydom/pull/161
