### ISSUE TITLE
Trying to read slot's assignedNodes in constructor fails

### ISSUE THREAD

**Issue by JanMiksovsky** [webcomponents/shadydom#165]
See http://jsbin.com/judoro/edit?html,output.

Reading a slot's flattened `assignedNodes` in a constructor fails under the polyfill. This works in native Shadow DOM, but under the polyfill, an attempt to read the slot's `assignedNodes` throws an exception: `TypeError: b is undefined`in webcomponents-lite.js. The offending line is in attach-shadow.js. ShadyRoot.prototype._addAssignedToFlattenedNodes is being invoked with the `asssigned` (sic) argument undefined, causing the reference `asssigned.length` to fail.

We have several components that trigger various checks in their constructor that ultimately cause a reading of `assignedNodes`, so this bug is blocking those components from working under the polyfill.

**Comment by JanMiksovsky** [comment]
We're now also hitting what appears to be the same bug in IE 11 even in components that don't explicitly referenced `assignedNodes` in the constructor.

See http://jsbin.com/sewixu/edit?html,output. That sets up two elements, one nested inside the other. Setting content on the outer element should assign that content to the inner element, but triggers an error in IE 11:

```
SCRIPT5007: Unable to get property 'length' of undefined or null reference
webcomponents-lite.js (135,358)
```

That location in webcomponents-lite.js looks like the same line in `_addAssignedToFlattenedNodes` implicated above.

**Comment by Zecat** [comment]
I'm facing this too by using a `<slot>` inside a slotted template.

A quick hack for webcomponentsjs#1.0.8
```html
<!-- insert this right after webcomponentsjs import -->
<script>
  var tmp = ShadowRoot.prototype.c;
  ShadowRoot.prototype.c = function(a, b) { if (b) tmp.call(this, a, b) }
</script>
```

**Comment by pdesjardins90** [comment]
Same thing over here. Tried the workaround too, but with webcomponentsjs#1.0.14 and it doesn't work.

**Comment by azakus** [comment]
Yep, I see where this is happening. It looks like if a slot is being distributed, it may not be initialized before nodes are distributed to it.
