### ISSUE TITLE
Angular 1.x Bindings Broken

### ISSUE THREAD

**Issue by jyounce** [webcomponents/shadydom#170]
Hi guys,

I'm trying to use web components (Polymer v2) inside of an angular v1 application.

When I use the ShadyDOM via including <script src="shadydom.min.js"> inside my app, my angular bindings break. I know it's related to the DOM because I've did a lot of googling trying to solve the issue.

So is it even possible to use the ShadyDOM inside of an angular app?

Any help would be much appreciated,

Judd

**Comment by bwolff** [comment]
Maybe this is related to https://github.com/webcomponents/webcomponentsjs/issues/754 which will be fixed by PR https://github.com/webcomponents/shadydom/pull/172

**Comment by jyounce** [comment]
Thanks Ben but unfortunately that did not work.

Seems like the wrap functions from the older [ShadowDOM](https://github.com/Polymer/ShadowDOM/tree/e61177c7d9c7247c625b3361aed2508945f827e0#wrap-and-unwrap) library is what is needed.

Is there anything equivalent to the wrap functions in ShadyDOM?

**Comment by TimvdLippe** [comment]
We have tests running on custom-elements-everywhere.com with AngularJS (https://custom-elements-everywhere.com/libraries/angularjs/results/results.html) and it appears to be working there. Given that this issue has been open for a while, I assume this issue has been resolved.
