### ISSUE TITLE
ShadyDOM breaks Template polyfill on IE11

### ISSUE THREAD

**Issue by Jeff17Robbins** [webcomponents/shadydom#179]
I wasn't sure where to write this up, and started over on the Template repo because the problem shows up as the template content not being inert on IE11.

Reported issue here: https://github.com/webcomponents/template/issues/21

This `get` added by ShadyDOM

```
  get isConnected() {
    var ownerDocument = this.ownerDocument;
    if (ownerDocument && ownerDocument.contains && ownerDocument.contains(this)) return true;
    var ownerDocumentElement = ownerDocument.documentElement;
    if (ownerDocumentElement && ownerDocumentElement.contains && ownerDocumentElement.contains(this)) return true;
```
treats the Template polyfill's `contentDoc.body` element as 'connected', which seems to be the source of the problem.

The last line of code returns `true`, despite the intent of the Template polyfill to create an inert document via 
```
var contentDoc = document.implementation.createHTMLDocument('template');
```

`contentDoc.body` passes the test of being contained by `contentDoc`, and in that sense is 'connected', but is meant to be inert.

Maybe ShadyDOM could check `document.title` and see the string `template` (already there from the Template polyfill!) and leave this document alone somehow?

**Comment by kaste** [comment]
FWIW your code of `isConnected` is probably outdated?

https://github.com/webcomponents/shadydom/blob/391af315e508e03fd5224eb8b4f6fdb76a1a86b5/src/patch-builtins.js#L83-L98

**Comment by Jeff17Robbins** [comment]
Thanks for the heads up; I'll re-test!

**Comment by TimvdLippe** [comment]
Closing this per above comment. Glad it has been resolved!
