### ISSUE TITLE
Error in Firefox: TypeError: c is null 

### ISSUE THREAD

**Issue by jogibear9988** [webcomponents/shadydom#183]
<img width="1452" alt="bildschirmfoto 2017-09-29 um 22 35 59" src="https://user-images.githubusercontent.com/364896/31035025-c1c700e0-a566-11e7-93bc-753124708430.png">

**Comment by jogibear9988** [comment]
with this plunker you can reproduce https://plnkr.co/edit/mggcVPrlbtNZ0PNgtyq6

**Comment by jogibear9988** [comment]
see also: https://github.com/webcomponents/webcomponentsjs/issues/854

**Comment by jogibear9988** [comment]
removed a little bit of the code: https://plnkr.co/edit/xWI7TuLZcBSUJDpqttLy

**Comment by jogibear9988** [comment]
when the map file is loaded the error seems to be in line:

https://github.com/webcomponents/shadydom/blob/4c0ef0fd3ef65538d9859412151d6558f140ab6d/src/patch-events.js#L304

**Comment by TimvdLippe** [comment]
This was fixed in #187 but not closed.

**Comment by jogibear9988** [comment]
sorry i forgot :-(
