### ISSUE TITLE
e.target throws TypeError

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#184]
(Originally filed here https://github.com/webcomponents/webcomponentsjs/issues/857)

To repro: http://jsbin.com/fewosow/1/edit?html,console,output
```js
document.addEventListener('mousedown', function(e) {
  setTimeout(function() {
    console.log(e.target); // throws TypeError
  }, 300);
})

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/jopeyaleme/edit?html,console,output
