### ISSUE TITLE
Mouse event not reaching target after getting dispatched

### ISSUE THREAD

**Issue by aniruddhand** [webcomponents/shadydom#197]
If a mouse event is dispatched programmatically to a target then it does not reach target if, in the MouseEvent constructor, target and relatedTarget values are same.

It happens due to condition:
https://github.com/webcomponents/shadydom/blob/cb84c2ef9fe126a7d707e634c44b6079c8bdf335/src/patch-events.js#L348

I am not sure if there is an issue with the check itself as it has been clearly mentioned in the comments that re-targeted target and relatedTarget must not be same.  Perhaps this check should not be made if target and relatedTarget are same in the first instance itself?

I have attached an example file with the issue. If, on line 29, el is replaced by null then event will eventually reach. This example file is a simplified use case of jsPlumb library which generates an event on another element (a canvas) when user starts dragging. When it dispatches "mousedown" event to canvas it sets relatedTarget same as target. Event is not reaching canvas and as a result dragging activity does not begin at all.

Initially I thought it is jsPlumb which is doing wrong by setting relatedTarget equal to the target. However, in Chrome (57.0.2987.110), which does not require shady dom polyfill, event is indeed reaching target. I see this issue in Firefox and IE which polyfill shady dom.

[related-target.zip](https://github.com/webcomponents/shadydom/files/1483195/related-target.zip)

**Comment by azakus** [comment]
Hmm, if I understand this correctly, the bug is that the `target === relatedTarget` check is happening for events that are not bubbling through a shadowroot.

This is separate from the fact that an event must be stopped if the `relatedTarget` and `target` are the same after it bubbles through a shadowroot according to the spec.

**Comment by aniruddhand** [comment]
Yes, you are right. It is not related to check itself. Hence I mentioned probably that check must not be performed in the first instance i.e when we are firing for the first time.

Thanks a ton @azakus!
