### ISSUE TITLE
Make sure setting class does not stomp scoping selector

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadydom#2]
When used with ShadyCSS, elements in shadowRoot's have a scoping class added to them. If `className` or `setAttribute('class', ...)` are used this should not remove the scoping selector.

**Comment by blasten** [comment]
Also, consider when the styles are reset via bindings. The following test case doesn't work:

```html
<dom-module id="x-foo">
  <template>
    <style>
      :host {
        display: block;
      }

      .red {
        color: red;
      }
    </style>
    <div class$="red [[customStyle]]">Red</div>
  </template>
  <script>
    Polymer({
      is: 'x-foo',
      properties: {
        customStyle: {
          type: String,
          value: ''
        }
      }
    });
  </script>
</dom-module>
<x-foo></x-foo>
```

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadydom/pull/54.

**Comment by frankiefu** [comment]
@sorvell Running the test @blasten provided, I am getting "class.html:12 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.(…)"

Seems to be happening on this line: https://github.com/webcomponents/shadycss/blob/master/src/ShadyCSS.js#L323
