### ISSUE TITLE
fail if text is null

### ISSUE THREAD

**Issue by noopole** [webcomponents/shadydom#203]
Whith Shadow DOM polyfill, if `textContent `is set to `null`, following line

https://github.com/webcomponents/shadydom/blob/ab69f88581ce511ee7d6937446c0ed3a3e0e1a6e/src/patch-accessors.js#L257

will fail. Should we add a test before?

Cf. [Stackoverflow question](https://stackoverflow.com/q/47822879/4600982)

**Comment by TimvdLippe** [comment]
Yes, feel free to add a test with the corresponding fix :)

**Comment by intervalia** [comment]
Thanks for working on this.

**Comment by limonte** [comment]
We are having the same issue:

![](https://i.imgur.com/pPrgiXp.png)
