### ISSUE TITLE
importNode doesn't clone template's content

### ISSUE THREAD

**Issue by bgotink** [webcomponents/shadydom#204]
### Description
`document.importNode(myTemplate, true)` should clone the template's content (as per [the spec](https://html.spec.whatwg.org/multipage/scripting.html#dom-template-content)), but it doesn't. Using `myTemplate.cloneNode(true)` does work as expected.

The `cloneNode` function in `logical-mutation.js` defers to the native `cloneNode` when cloning template elements. The `importNode` function in that same file doesn't do that, so I suspect that might be the issue.

#### Live Demo
http://jsbin.com/gamodebani/1/edit?html,console,output

Comment the `ShadyDOM = { force: true };` on Chrome or Safari to see how it is expected to work.

#### Steps to Reproduce

```
const tpl = document.createElement('template');
tpl.content.appendChild(document.createTextNode('foo'));

console.log(document.importNode(tpl, true).content.childNodes);
// Without ShadyDOM: NodeList [text]
// With ShadyDOM: [item: ƒ]

console.log(tpl.cloneNode(true).content.childNodes)
// Without ShadyDOM: NodeList [text]
// With ShadyDOM: [text, item: ƒ]
```

#### Expected Results
The console should show two lists containing one text element.

#### Actual Results
When using `document.importNode` with ShadyDOM the resulting array is empty.

### Browsers Affected

all

### Versions
- webcomponents: v1.0.20

**Comment by TimvdLippe** [comment]
Confirmed that with just the template polyfill, it is working as intended: http://jsbin.com/qadiferiye/edit?html,console,output
