### ISSUE TITLE
master is broken because of webcomponents/custom-elements/src/Patch/Node.js#L167-L205

### ISSUE THREAD

**Issue by limonte** [webcomponents/shadydom#206]
![](https://i.imgur.com/fZ9RQ94.png)

Failing build: https://travis-ci.org/webcomponents/shadydom/builds/326507573?utm_source=github_status&utm_medium=notification

Build is failing after added tests in https://github.com/webcomponents/shadydom/pull/205

For some reason, `custom-elements`'s patch for `textContent` assigning `'null'` instead of `''` and `'undefined'` instead of `''`.
 
Related code: https://github.com/webcomponents/custom-elements/blob/1b2ad174411aab7cccb8231214399bb033dd5d49/src/Patch/Node.js#L167-L205

**Comment by limonte** [comment]
Here's the fix for `custom-elements`: https://github.com/webcomponents/custom-elements/pull/130

**Comment by TimvdLippe** [comment]
This appears to be addressed. Our builds are green again.
