### ISSUE TITLE
ShadyDOM breaks partial table templates

### ISSUE THREAD

**Issue by justinfagnani** [webcomponents/shadydom#208]
### Description

When ShadyDOM is enabled, partial table templates like:

```
const template = document.createElement('template');
template.innerHTML = '<tr></tr>';
```

don't have any children.

#### Live Demo
https://codepen.io/justinfagnani/pen/ypEdQo?editors=1111

#### Steps to Reproduce
1. Create a `template`
2. Set its `innerHTML` to "<tr></tr>"
3. Read its `innerHTML`, it's now blank

### Browsers Affected
All

### Versions
- shadydom: 1.0.11

**Comment by TimvdLippe** [comment]
After https://github.com/webcomponents/template/pull/39 has been merged, we have to reinvestigate if this has been addressed.
