### ISSUE TITLE
Shady adds a ton of comments to head

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/shadydom#209]
_From @ebidel on May 23, 2016 21:11_

Using many components in an app adds a lot of needless comments to the `<head>`.

![screen shot 2016-05-23 at 2 03 01 pm](https://cloud.githubusercontent.com/assets/238208/15484584/89e07140-20ef-11e6-8b71-c3079ad758f1.png)

Do we need to add these? Would be cool to remove as a nice microperf opt and DOM cleanup.

_Copied from original issue: Polymer/polymer#3673_

**Comment by TimvdLippe** [comment]
_From @43081j on May 24, 2016 8:26_

These appear to be a placeholder so any CSS can be appended to the DOM in the correct order (always after its associated comment).

Maybe we could instead keep ordering state in memory rather than DOM.

**Comment by azakus** [comment]
This is actually in ShadyCSS, but it is correct that these are used for positioning polyfilled styling.
Not really interested in making this more optimal at this time.
