### ISSUE TITLE
onfocus property is not polyfilled

### ISSUE THREAD

**Issue by rslawik** [webcomponents/shadydom#212]
### Description
Event handlers added using properties are not polyfilled.
Example:
```
element.onfocus = (event) => { console.log(event); };
```

#### Live Demo
http://jsbin.com/solewuwuva/edit?html,output

#### Steps to Reproduce
Assign a function to `onfocus` property.

#### Expected Results
Assignment is handled by the polyfill.

#### Actual Results
Function is added as an event handler directly on the element. When it is invoked it receives a patched event and `event.currentTarget` is incorrect (`Window` in the demo).

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- webcomponents: vX.X.X

**Comment by sorvell** [comment]
I think it should be straightfoward to polyfill this. In the meantime, you should be able to workaround the issue by using `addEventListener`.

Dealing with the attribute is probably not worth it since this is such an anti-pattern.

**Comment by rslawik** [comment]
Unfortunately, I can't easily modify the code using the property. In my case it is the GWT framework adding the handler.
That means that without changes to either the polyfill or GWT, I can't use Polymer 2 together with GWT.

**Comment by eavichay** [comment]
@sorvell I disagree. When you write a component that controls your inner HTML you can use `target.on<Event> = e => {whatever()}`. Though it is not "best practice" it is used widely and It is best for all of us to support even "bad" practices - at least in the technical manner.

**Comment by rslawik** [comment]
I ended up writing a little polyfill for `onfocus` and `onblur` that delegates to `addEventListener`.

**Comment by rslawik** [comment]
Yes, I created a small polyfill that delegates `onfocus = handler` to `addEventListener('focus', handler)`.

Something like:
```
var nativeHTMLElement = (window['customElements'] && window['customElements']['nativeHTMLElement']) || HTMLElement;

Object.defineProperty(nativeHTMLElement.prototype, 'onfocus', {
    enumerable: true,
    configurable: true,
    get: function() {
      return this['__onfocus__'];
    },
    set: function(newValue) {
      if (this['__onfocus__']) {
        this.removeEventListener('focus', this['__onfocus__']);
      }
      this['__onfocus__'] = newValue;
      if (newValue) {
        this.addEventListener('focus', newValue);
      }
    },
});
```
Similarly for `onblur`.
