### ISSUE TITLE
In some browsers grab html content (that has WC with ShadyDOM) with innerHTML and pastit later with innerHTML corrupts content.

### ISSUE THREAD

**Issue by jorrete** [webcomponents/shadydom#23]
Hi,

[Example](https://gist.github.com/jorrete/23981fb5cc027aae0358d347eef45ef6)

I found the problem using Qunit. Qunit seems to grab the content of #fixtures as innerHTML and pastes it in each test. 

What happens is that the content gets corrupted (tested in Firefox Nightly, Chrome, Safari preview 13).

In the example that I've attached you can see how some shadow dom it's duplicated.

Thanks!

**Comment by TimvdLippe** [comment]
I am not sure what the expected results are in the provided example. Could you produce a JSBin which shows the issue and states what the expected values are?

**Comment by TimvdLippe** [comment]
Closing per above comment. Please open a new issue once you have a reproduction case.
