### ISSUE TITLE
Document styles leak in custom elements

### ISSUE THREAD

**Issue by lpellegr** [webcomponents/shadydom#232]
### Description

Let's say we have a page where the CSS style for `p` elements is overridden to set `margin-top` to 0. The page loads a custom element whose its template is made of 3 `p` elements. If I load the page with Chrome, `p` elements have default margins. If I load with Firefox, `p` elements have `margin-top` set to  0.

If I remove the CSS definition for `p` elements from the main document, then the issue disappears. This lets me suppose there is something wrong with a polyfill loaded by Firefox.

#### Live Demo
https://glitch.com/edit/#!/button-organ?path=index.html:16:2

#### Steps to Reproduce

Simply load the previous live demo on Chrome and Firefox (tested with version 59)  to see the problem.

#### Expected Results

Main document CSS styles do not leak in custom elements: p elements have default margin.

#### Actual Results
Main document CSS styles leak in custom elements.

### Browsers Affected

- [ ] Chrome
- [X] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- webcomponents: v1.2.0

**Comment by lpellegr** [comment]
Is there a workaround? If I set `p { all: initial }` at the custom-element level, then `p` elements are inlined. The only solution I see for now is to override most common attributes for `p` elements but it looks crazy. Are there any other solutions?

**Comment by TimvdLippe** [comment]
This is a known limitation of ShadyCSS: https://github.com/webcomponents/shadycss#document-level-styling-is-not-scoped-by-default

**Comment by lpellegr** [comment]
@TimvdLippe Thanks for the link. After ready the page, it seems that _CustomStyleInterface_ could be a solution to the problem I described. Is there a document or an example somewhere that explains its purpose and how to use it?

**Comment by TimvdLippe** [comment]
Examples are included in the same document (https://github.com/webcomponents/shadycss/blob/master/README.md#about-customstyleinterface) as well as the `examples` folder.
