### ISSUE TITLE
removeEventListener broken if same callback is used for 2 events

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#24]
Using the same callback for 2 different events results in the event listener not being removed. It must have something to do with [this assignment](https://github.com/webcomponents/shadydom/blob/master/src/event-mixin.js#L248)

``` js
function logEventType(event) {
  console.log(event.type);
}

document.addEventListener('mousedown', logEventType);
document.addEventListener('mouseup', logEventType);
console.log('added listeners');

setTimeout(function() {
  document.removeEventListener('mousedown', logEventType);
  document.removeEventListener('mouseup', logEventType);
  console.log('removed listeners');
}, 1000);
```

**Comment by treshugart** [comment]
I could definitely reproduce it. Was using it [here](https://github.com/skatejs/skatejs/blob/4518bd8a386f42ea0dae7e42dde2cc327245c602/test/unit/vdom/events.js#L144) and it was causing [this test](https://github.com/skatejs/skatejs/blob/4518bd8a386f42ea0dae7e42dde2cc327245c602/test/unit/vdom/events.js#L191) to fail.
