### ISSUE TITLE
Distribution broken when using native custom elements and parser generated nodes

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadydom#245]
Recently merged https://github.com/webcomponents/shadydom/pull/222 introduced an issue with re-distribution when creating shadowRoots during document load. 

Support for this was added to interoperate with native custom elements which can create shadowRoot's while the document is parsing. Fixing it looks complicated and instead this change should be rolled back.

Instead a flag can be added to specifically defer native custom element's connection state processing until document load has occurred. Since this may have negative performance impact, the flag should only be used during testing.

**Comment by smalluban** [comment]
@sorvell I am not sure, but it can be related to https://github.com/webcomponents/shadydom/issues/247.
