### ISSUE TITLE
Once shadowdom is created, the element doesn't hanle events with handleEvent method.

### ISSUE THREAD

**Issue by jorrete** [webcomponents/shadydom#25]
Hi,

Once shadowdom is created, the element doesn't hanle events with handleEvent method.

Error in firefox:
`
TypeError: b is not a function
`

[Example](https://gist.github.com/jorrete/9a8e0b05ba8f5dcda1e4f483f813108b)

Thanks!

**Comment by sorvell** [comment]
Sorry for the long delay on this, but it is finally fixed as shown here: 

http://jsbin.com/qosiso/edit?html,output
