### ISSUE TITLE
Event listeners on slot elements do not work

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/shadydom#252]
_From @web-devel on June 22, 2018 9:58_

Event listener added to `slot` element does not work with polyfill
See the following bin:
https://jsbin.com/zijecod/10/edit?html,output

_Copied from original issue: webcomponents/webcomponentsjs#958_

**Comment by sorvell** [comment]
I think we can address this in a similar way that we do event listeners on `shadowRoot`s. We can listen on the slot parent and then filter any events that do not contain the <slot> in the `composedPath`.
