### ISSUE TITLE
distribution is not working correctly

### ISSUE THREAD

**Issue by frankiefu** [webcomponents/shadydom#27]
- checkout shop `2.0-preview` branch:
  `git clone git@github.com:Polymer/shop.git; cd shop; git checkout 2.0-preview; git pull; bower install;`
- run the app with `shadydom="true"` and you will see the tabs are not showing up

If you inspect/debug it you can see `shop-tab`'s are there but somehow it's not in the render tree.

![screen shot 2016-09-26 at 6 05 47 pm](https://cloud.githubusercontent.com/assets/116360/18856885/dff6bc2e-8413-11e6-8217-88bad5430ba4.png)

**Comment by sorvell** [comment]
I believe it's this issue: https://github.com/webcomponents/shadydom/issues/5.

**Comment by sorvell** [comment]
Fixed.
