### ISSUE TITLE
Question: Support for extending Native Elements

### ISSUE THREAD

**Issue by ryansolid** [webcomponents/shadydom#278]
The polyfill's customElements.define only takes the first 2 arguments not passing through the third optional argument ({extends: 'a'} etc...). Is there any reason you wouldn't just pass the 3rd argument through to allow the polyfill to run in environments that have implemented this Spec? Even if the webcomponents custom element polyfill doesn't support it as of yet is there harm in passing it through?

**Comment by azakus** [comment]
We're not interested right now in implementing extending elements other than HTMLElement right now. The browsers are not in agreement about implementing this feature, and forcing polyfills on the browsers without is is not a good result for end-users.
