### ISSUE TITLE
attribute selectors with colons are corrupted

### ISSUE THREAD

**Issue by LarsDenBakker** [webcomponents/shadydom#280]
When attribute selectors contain colons the scope name class is incorrectly added to the attribute. See: https://jsbin.com/hatorodeja/edit?html,output

The original CSS:
```
[foo="foo:bar"] {
  background-color: blue;
}
        
[foo="foobar"] {
  background-color: blue;
}
```

is scoped as:

```
[foo="foo.my-element:bar"] {
  background-color: blue;
}

[foo="foobar"].my-element {
  background-color: blue;
}
```

**Comment by TimvdLippe** [comment]
This was actually an issue in ShadyCSS in interplay with ShadyDOM. PR is up: https://github.com/webcomponents/shadycss/pull/211
