### ISSUE TITLE
Shadydom enforces capturing phase in IE 11

### ISSUE THREAD

**Issue by attilapuskas** [webcomponents/shadydom#289]
### Description
If the event listeners are added via properties (like in GWT for example) then using shadydom in IE 11 could cause several issues because the events will use the capturing phase logic and not the default/expected bubbling phase.

#### Live Demo
https://jsbin.com/tojafuvowo/1/edit?html,js,output

#### Steps to Reproduce
1. Create "_outer_" and "_inner_" element so that _inner_ is a descendant of _outer_.
2. Add event listener using properties, for example _onmousedown_.

#### Expected Results
Triggering a related event should be dispatched first on the children if that was the target.

#### Actual Results
The event is dispatched first on parent (capturing phase).

### Browsers Affected
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [X] IE 11

### Versions
- webcomponents/shadydom: v1.1.0 and above (it is not reproducible in 1.0.14)

**Comment by kenyerr** [comment]
Strange thing but removing the empty object from that [line](https://github.com/webcomponents/shadydom/blob/5e1e02f00cf460cffed4c23cd247b636c73a967b/src/patch-builtins.js#L259) solves the issue. As I've debugged it the _optionsOrCapture_ is handled property in the [patch-events.js](https://github.com/webcomponents/shadydom/blob/5e1e02f00cf460cffed4c23cd247b636c73a967b/src/patch-events.js#L332) but still IE 11 somehow uses capturing phase if it is used.

The following test should be ok for that. I'll create a PR if I found time for that soon.

```
    test('should use bubbling phase for event listeners added via properties', function () {
      const parent = document.createElement('div');
      parent.id="parent";
      document.body.appendChild(parent);
      const child = document.createElement('div');
      child.id="child";
      parent.appendChild(child);

      const parentMouseDownSpy = sinon.spy();
      const childMouseDownSpy = sinon.spy();

      parent.onmousedown = parentMouseDownSpy;
      child.onmousedown = childMouseDownSpy;

      child.dispatchEvent(new MouseEvent('mousedown', { bubbles: true, composed: true }));

      assert.isTrue(childMouseDownSpy.calledBefore(parentMouseDownSpy), 'Event handler on child should be called first');
    });
```

**Comment by web-padawan** [comment]
Yeah, that empty object forces capture phase in browsers not supporting event listener options Looks like the [intervention](http://tonsky.me/blog/chrome-intervention/) for passive event listeners strikes again.
