### ISSUE TITLE
infinite recursion of flush with dom-repeat

### ISSUE THREAD

**Issue by bicknellr** [webcomponents/shadydom#29]
#### Description
The following demo recurses infinitely through ShadyDOM flushes.

#### Live Demo
http://plnkr.co/edit/Ef4MUl7C2UXQrUNYyoKn

#### Versions
- Polymer: 2.0-preview branch
- webcomponents: v1 branch
- shadydom: master branch
- shadycss: master branch
- custom-elements: master branch

**Comment by blasten** [comment]
I'm also hitting this problem.
