### ISSUE TITLE
getElementById with empty string returns document

### ISSUE THREAD

**Issue by dlockhart** [webcomponents/shadydom#300]
### Description

This obviously only applies to browsers who require the shadydom polyfill -- it occurs in both IE11 and Edge for me, or all browsers if you force the polyfill ON.

The native `document.getElementById` when passed an empty string as the ID parameter returns `null`. However, when the shadydom polyfill [overrides the native function](https://github.com/webcomponents/shadydom/blob/6ced5972f8394dcd4acbd16087051b256cadae22/src/patches/DocumentOrFragment.js#L19), the behavior changes such that the root `<html>` element is returned instead.

This is likely because `document.documentElement.id` (the `<html>` element) is the empty string, so when it's doing its comparisons it thinks it has a match.

#### Live Demo

Live demo here. This forces shadyCSS on, so `document.getElementById('')` will be the `<html>` element in all browsers:
[https://jsbin.com/dinibiwije/1/edit?html,console](https://jsbin.com/dinibiwije/1/edit?html,console)

#### Steps to Reproduce

1. Include the ShadyCSS polyfill
2. Call `document.getElementById('')`

#### Expected Results
This call should return `null`.

#### Actual Results
The `<html>` element is returned.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Edge
- [ ] Safari 9
- [ ] Safari 8
- [x] IE 11

### Versions
- webcomponents: v2.2.1

**Comment by TimvdLippe** [comment]
Feel free to send a PR with a fix for this :smile: Should be a simply `if (selector === '') { return null; }`
