### ISSUE TITLE
childElementCount causes error without children property

### ISSUE THREAD

**Issue by attilapuskas** [webcomponents/shadydom#302]
### Description
Error thrown when calling `childElementCount` on a svg element (without children property).

#### Live Demo
https://jsbin.com/naxefinaxu/edit?html,js,console

I've tested on IE 11.194.17763.0 but I guess the main point is to have a null `children`.

Perhaps [childElementCount patch](https://github.com/webcomponents/shadydom/blob/6ced5972f8394dcd4acbd16087051b256cadae22/src/patch-native.js#L257) should check whether the children is absent or not. As this seems to be the case with the native calls.

**Comment by TimvdLippe** [comment]
Yup, seems like a trivial fix. Feel free to open a PR and add a regression test!
