### ISSUE TITLE
Potential copy-paste issue in patch-native.js

### ISSUE THREAD

**Issue by attilapuskas** [webcomponents/shadydom#307]
While checking the relevant code for the #302 I have noticed the below mentioned line where perhaps the `Document` should be used instead of the `DocumentFragment`? If indeed the `DocumentFragment` the correct one then a little comment about the motivation would be really cool.

https://github.com/webcomponents/shadydom/blob/e3471cf4461328e0e97afb4d2e5743e7d3d9d934/src/patch-native.js#L397

**Comment by sorvell** [comment]
Yup, that should definitely be `Document`.

**Comment by attilapuskas** [comment]
Thank you!
