### ISSUE TITLE
Add Browser Compatibility to Readme

### ISSUE THREAD

**Issue by EisenbergEffect** [webcomponents/shadydom#309]
First, let me just say how thankful I am to everyone who has worked on this polyfill. I built simple v0 and v1 fallback implementations of Shadow DOM for Aurelia a few years back and it was tricky work. In our vNext of Aurelia, we're looking to adopt shadow DOM natively and recommend this polyfill for browsers that still lack the feature. I'd like to make one request of the readme that I think would help us and others looking to use this polyfill. Would you mind adding a section that describes the browser compatibility? If I've somehow missed it, please point me to the right location. Thanks!

**Comment by TimvdLippe** [comment]
We have a browser compatibility section in the main webcomponentsjs polyfill: https://github.com/webcomponents/webcomponentsjs#browser-support

**Comment by EisenbergEffect** [comment]
Thanks for the link @TimvdLippe ! It might be cool to link to the same page from this repo's readme for greater visibility. Would you accept a PR for that? I'd be happy to write it up.

**Comment by TimvdLippe** [comment]
Sure!
