### ISSUE TITLE
`track` listeners broken in Shady DOM

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/shadydom#4]
_From @keanulee on August 12, 2016 17:32_

``` html
<html>
<head>
<script src="../webcomponentsjs/webcomponents-lite.js"></script>
<link rel="import" href="polymer.html">
</head>

<body>
<dom-module id="x-elem">
  <template>
    <h1>Hello world</h1>
  </template>

  <script>
    Polymer({
      is: 'x-elem',

      listeners: {
        'track': 'track'
      },

      track: function(e) {
        console.log(e);
      }
    });
  </script>
</dom-module>

<x-elem></x-elem>

</body>
</html>
```

As soon as you start tracking on the text:

![image](https://cloud.githubusercontent.com/assets/1319720/17631198/eaa8986e-6077-11e6-9f7f-11a67fba7377.png)

Seems to be related to the patched `removeEventListener` code. cc @azakus 

_Copied from original issue: PolymerLabs/alacarte#55_

**Comment by kevinpschaaf** [comment]
_From @azakus on August 12, 2016 17:44_

ShadyDOM event patching doesn't check that the second arg is actually a function.

**Comment by TimvdLippe** [comment]
Appears to be fixed: http://jsbin.com/tenotal/1/edit?html,console,output
