### ISSUE TITLE
Release plans

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/shadydom#42]
Sorry for the annoying question, but are there any plans for a release soon? Is there anywhere to track it? Can I help to get this release soon?

If not, a release tracking issue or something would be awesome, since on could get a feeling for the current state and progress.

I would like to start writing v1 elements, but can't without a polyfill (obviously).

Thank you very much.

**Comment by SerkanSipahi** [comment]
v1 is available in chrome v54 and canary

**Comment by SerkanSipahi** [comment]
Chrome v54 and Chrome Canary v56 supports shadowDom v1
```js
let supportsShadowDOMV1 = !!HTMLElement.prototype.attachShadow;
console.log(supportsShadowDOMV1) // will log "true"
```

**Comment by lukasoppermann** [comment]
Thanks, but I was wondering when this polyfill will be released and tagged.

**Comment by SerkanSipahi** [comment]
I think the community can speed up the release date for stable version. We should this polyfill for finding bugs :)

**Comment by SerkanSipahi** [comment]
See (below) awesome articles which explain with many examples how shadowDom v1 work. You can try them for finding bugs !

- http://hayato.io/2016/shadowdomv1/
- https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom

**Comment by lukasoppermann** [comment]
Thanks but this is totally not my question. I know how it all works, I want to know when this polyfill will get a tagged version.

**Comment by SerkanSipahi** [comment]
When the time comes. I dont know. Use it. Resort bugs and if you cant find bugs for your usecase everything is fine :)

**Comment by lukasoppermann** [comment]
Well, I was actually asking the maintainer of the repo. So I guess I will just wait until they answer. Thanks anyway.

**Comment by matthewp** [comment]
Same here, any reason not to do an `npm publish` @sorvell ? I know it's only 0.0.1, but release early and often and all that goodness :)

**Comment by treshugart** [comment]
To @matthewp's point, we're having to do this currently: https://github.com/skatejs/web-components/pull/28/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33. Not bad, but 0.x releases make sense for this :)

**Comment by sorvell** [comment]
Sorry for the slow response on this and we know the current state is annoying. There are a couple of bugs we just feel better about fixing before doing an initially tagged release, in particular https://github.com/webcomponents/shadydom/issues/7. We're hoping to dive into this asap so release should hopefully be pretty soon.

**Comment by TimvdLippe** [comment]
The polyfill is now production ready and successfully used to build a website based on v1 elements. The latest version of this package is available at https://www.npmjs.com/package/@webcomponents/shadydom
