### ISSUE TITLE
insertRow called under shadow DOM results in empty childNodes array on parent

### ISSUE THREAD

**Issue by Maxlufs** [webcomponents/shadydom#43]
This issue is found under shadow DOM v1, this happens both in chromium 53.0.2785 and the polyfill under FF.

``` js
var x = document.createElement('div');
x.attachShadow({mode:'open'});
var shadowRoot = x.shadowRoot;
shadowRoot.appendChild(document.createElement('table'));
shadowRoot.firstChild.insertRow();
console.log(shadowRoot.firstChild.childElementCount); // correctly return 1
console.log(shadowRoot.firstChild.childNodes); // incorrectly return [ ] instead of [<tbody></tbody>]
```

`childNodes` returns correct array under v0 implementation.
`childNodes` returns correct array if `appendChild(document.createElement('tr'))` was used instead.

**Comment by Maxlufs** [comment]
This issue only appears when shadydom polyfill is included in the page.
installed from `bower install webcomponents/shadydom` on 10/20/2016

**Comment by tuespetre** [comment]
Are you saying this occurs with the *native* Shadow DOM v1 in Chromium? If so would you be able to test Safari as well, I'm interested to know...

**Comment by tuespetre** [comment]
Do you have `window.ShadyDOM = { force: true };` or anything like that? Just curious, that may affect Chrome.

**Comment by tuespetre** [comment]
I've put in a PR for the 'read' stuff on the family of table-related elements. There will still need to be some work done to properly handle mutation-related things like `deleteRow()`, `deleteCell()`, `deleteTHead()`, etc.

**Comment by TimvdLippe** [comment]
This appears to be fixed: http://jsbin.com/fodagep/2/edit?html,console,output
