### ISSUE TITLE
parentNode not updated when element w/ shadowRoot is removed from its parent

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#44]
After removing `el` from its parent, `el.parentNode` is not updated (tested on firefox)

``` html
<script src="../shadydom/shadydom.min.js"></script>

<div id="myDiv"></div>
<script>
  const el = document.querySelector('#myDiv');
  el.attachShadow({mode: 'open'});
  el.parentNode.removeChild(el);
  console.log(document.body.contains(el)); // false (correct)
  console.log(el.parentNode); // <body> (should be null)
</script>
```

**Comment by sorvell** [comment]
Thanks for the minimal repro. It is currently required that any element from/to which an element with Shadow DOM is appended/removed must be "patched". This requirement will be removed soon when https://github.com/webcomponents/shadydom/issues/7 is addressed.

As a workaround in the meantime, you can call `ShadyDOM.patch` on the element to/from which you are adding/removing the element with Shadow DOM.

**Comment by bicknellr** [comment]
This also spills over into `getRootNode` and `Polymer.dom(...).getOwnerRoot` which ends up being a problem for iron-menu-behavior: [implementation](https://github.com/PolymerElements/iron-menu-behavior/blob/eb20ed867c3bd4a019112339ebeb8e35a8764129/iron-menu-behavior.html#L177), [tests](https://github.com/PolymerElements/iron-menu-behavior/blob/eb20ed867c3bd4a019112339ebeb8e35a8764129/test/iron-menu-behavior.html#L152).

**Comment by bicknellr** [comment]
Is [this line](https://github.com/webcomponents/shadydom/blob/e4a8be7b4dceb94b79de10ee450848a339ad1a58/src/tree.js#L59) meant to be commented out?

**Comment by bicknellr** [comment]
Actually, I might be wrong about this being the problem with `getRootNode`: in the particular case I've been looking at, 'node.__ownerShadyRoot` isn't correct, so it might be unrelated to `parentNode`.

**Comment by bicknellr** [comment]
This looks like it's been fixed: http://jsbin.com/pihami/1/edit?html,console,output

**Comment by sorvell** [comment]
Thanks for verifying @bicknellr.
