### ISSUE TITLE
ParentNode & ChildNode methods not patched

### ISSUE THREAD

**Issue by tuespetre** [webcomponents/shadydom#45]
In particular, these methods:

- `ParentNode`
  - `append(...nodes)`
  - `prepend(...nodes)`
- `ChildNode`
  - `before(...nodes)`
  - `after(...nodes)`
  - `replaceWith(...nodes)`
  - `remove()`

I found this out because Firefox was locking up on a `var child = void 0; while(child = parent.firstChild) child.remove();` loop. 😛

**Comment by F2X** [comment]
Same issue when wrapping and manipulate a svg with d3.js inside a polymer element. Redraw is not triggered on node manipulation (e.g. insertAdjacentHTML)

**Comment by TimvdLippe** [comment]
This appears to be working properly now: http://jsbin.com/jaqaxav/2/edit?html,console,output
