### ISSUE TITLE
Problem with getElementById on shadowRoot

### ISSUE THREAD

**Issue by cyrilletuzi** [webcomponents/shadydom#52]
In a custom element, I'm trying something like this : 

```
this.elementShadow = this.attachShadow({ mode: 'open' });
this.elementShadow.innerHTML = `<div id="my-id"></div>`;
this.elementShadow.getElementById('my-id');
```

It's OK in a browser with native support, but using the polyfill in a browser not supporting ShadowDOM v1 (Firefox for example), it returns `null`.

It works if I do : 
```
this.elementShadow.querySelector('#my-id');
```

**Comment by sorvell** [comment]
Confirmed. We need to add support for patching `getElementById`.
