### ISSUE TITLE
Need full DocumentOrShadowRoot support

### ISSUE THREAD

**Issue by treshugart** [webcomponents/shadydom#55]
Seems some, or all, of the following are missing: https://www.w3.org/TR/shadow-dom/#extensions-to-the-documentorshadowroot-mixin.

It's breaking our integration with ProseMirror at the moment.

**Comment by dam0vm3nt** [comment]
see also https://github.com/webcomponents/shadydom/issues/113 ?

**Comment by olegomon** [comment]
@treshugart We have the same issue with our ProseMirror integration and Polymer v2. Did you have any chance to make ProseMirror work in a Shady Dom environment?

**Comment by treshugart** [comment]
No but @samthor was working on some stuff that may help.

**Comment by samthor** [comment]
My contributions are just the polyfill you mentioned in [#113](https://github.com/webcomponents/shadydom/issues/113), @olegomon .

**Comment by azakus** [comment]
Closing in favor of https://github.com/webcomponents/polyfills/issues/66
