### ISSUE TITLE
wrong content distribution

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#56]
We have a `x-list` with `x-item` children; `x-item` is an element that fires `item-selected` when its selection changes:
```html
<!-- in index.html -->
<x-list>
  <x-item>Item</x-item>
</x-list>
```

`x-list` shadowRoot distributes its content in `x-items`, and listens for events fired by `x-items`
```html
<!-- x-list template -->
<span>selection change count: [[selectionChangeCount]]</span>
<x-items on-item-selected="_onItemSelected">
  <slot></slot>
</x-items>
```

When ShadyDOM is in use, distribution looks wrong in the dev console, and as a consequence `x-list._onItemSelected` is never invoked http://output.jsbin.com/piwoloc/1/?wc-shadydom=true
![screen shot 2016-11-22 at 11 10 20 am](https://cloud.githubusercontent.com/assets/6173664/20538025/4f15ac34-b0a4-11e6-8be2-64bb4d0ef6c2.png)
^ the `x-item` elements should be children of `x-items`.

**Comment by sorvell** [comment]
Seems be ok if the `customElements` polyfill is used. Related to https://github.com/webcomponents/shadydom/issues/5.

http://jsbin.com/dipudo/edit?html,output

**Comment by valdrinkoshi** [comment]
Yeah, that solves the above scenario.
In my actual scenario I see issues in the distribution on `x-dropdown-menu.attached`, see this example http://jsbin.com/yicaluv/5/edit?html,output
Looks like that when `x-dropdown-menu.attached` is called, the `paper-listbox.assignedSlot` is still `null`. If we flush then the problem is solved.
@sorvell any suggestions?

**Comment by sorvell** [comment]
Accessing `assignedSlot` can force distribution to complete.

**Comment by valdrinkoshi** [comment]
Whose `assignedSlot` & when? Tried on `attached` but no success http://jsbin.com/yicaluv/7/edit?html,output

**Comment by sorvell** [comment]
We got a little eschew on the `assignedSlot` point. The issue is that since distribution is asynchronous under ShadyDOM, an element may have a shadowRoot with a `<slot>` and a child that should be *but is not yet* distributed to that slot. I will go ahead and change ShadyDOM's `assignedSlot` accessor such that accessing it will synchronously trigger distribution. This should fix that inconsistency.

**Comment by sorvell** [comment]
Note, after https://github.com/webcomponents/shadydom/pull/64 lands, ShadyDOM should be more compatible with native custom elements. While testing this we found a related chrome bug listed here for reference: https://bugs.chromium.org/p/chromium/issues/detail?id=676365.

**Comment by valdrinkoshi** [comment]
Yeah, sorry for the confusion.
The main problem faced is that elements don't get the effective children distributed on attached.
e.g. I need to get the effective child nodes of a `<slot>` (I use the `Polymer.dom` API `getDistributedNodes`) and expect the distribution to be done on `attached` http://jsbin.com/cilurux/4/edit?html,console,output
I switched to the branch of #64 and it does seem to fix the issue.

**Comment by valdrinkoshi** [comment]
Looks like this is fixed. Closing.
