### ISSUE TITLE
Tests needed for the focus/blur changes

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/shadydom#6]
_From @notwaldorf on August 17, 2016 22:55_

It would be great to have unit and smoke tests for the following cases:
- focus is coming from a custom element (i.e. clicking on a `paper-button`)
- focus is coming from the shadow dom (i.e. clicking on an `input` inside a `paper-input`)
- focus is moving in the shadow dom (i.e. switching focus from an `input` to another `input` inside a `paper-input`
- focus is coming from the light dom (i.e. clicking on an `input` distributed in a `paper-button`)
- focus is moving in the ling dom (i.e. switching focus from an `input` to another `input` distributed in a `paper-button`

Please feel free to add more!

_Copied from original issue: PolymerLabs/alacarte#68_

**Comment by kevinpschaaf** [comment]
_From @valdrinkoshi on August 18, 2016 18:28_

It would be great to test focus/blur together with tap/click.
There is already an issue opened for [considering removing `tap`](https://github.com/PolymerLabs/alacarte/issues/40)

**Comment by kevinpschaaf** [comment]
_From @notwaldorf on August 22, 2016 18:20_

I can take this!

**Comment by sorvell** [comment]
@notwaldorf  Yes, please take this! Thanks!

**Comment by TimvdLippe** [comment]
This appears to be fixed in https://github.com/webcomponents/shadydom/blob/master/tests/smoke/focus-api.html and https://github.com/webcomponents/shadydom/blob/master/tests/smoke/focus.html
