### ISSUE TITLE
In Firefox when ShadyDOM is loaded carets disappear from <input>

### ISSUE THREAD

**Issue by patrickarlt** [webcomponents/shadydom#61]
When ShadyDOM is loaded in Firefox (50.0.2) all `<input>` elements loose their caret when focused.

![screen shot 2016-12-05 at 11 28 42 am](https://cloud.githubusercontent.com/assets/378557/20899428/47c07708-badf-11e6-816b-5be1b9600a62.png)

You can reproduce with the following HTML or in http://jsbin.com/rifakizoju/edit?html,output

```html
<!DOCTYPE html>
<html>
<head>
  <title>JS Bin</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <script src="https://cdn.rawgit.com/webcomponents/shadydom/master/shadydom.min.js"></script>
  <style>
    input {
      display: block;
      font-size: 1rem;
    }
  </style>
</head>
<body>
  <label>
    Will not show caret when input it focused&hellip;
    <input type="text">
  </label>
</body>
</html>
```

All other functionality of the`<input>` remains appears to be fine.

**Comment by patrickarlt** [comment]
Can anyone else reproduce this? I also tried reseting Firefox. This seems like a big UX bug since it prevents valuable user feedback even outside of components using ShadowDOM.

**Comment by sorvell** [comment]
Can confirm this issue. It looks like it's due to the way we're handling focus/blur events. @azakus would you mind investigating?

**Comment by patrickarlt** [comment]
@sorvell @azakus any progress on this? I was hoping to begin testing some custom elements based on ShadyDOM for production in the next few months but this is blocking that and I am considering just sticking with the v0 polyfill for now.

**Comment by notwaldorf** [comment]
@azakus ping to put it back on the radar, since this is a bit of a big one :(

**Comment by daKmoR** [comment]
If you comment out one line
https://github.com/webcomponents/shadydom/blob/v1.0.0-rc.1/src/patch-events.js#L380

then everything works fine in Firefox. Chrome still works as well.

I'm not sure if removing that line is a viable solution... maybe just ignore it for Firefox?
If anyone could clarify I could create a full request.

Not being able to properly use input elements with Firefox is a really bummer... so let's fix that :)

**Comment by daKmoR** [comment]
any update regarding this?

**Comment by daKmoR** [comment]
thx 👍 :)

**Comment by OneBitAhead** [comment]
👍

**Comment by robert-gogolan** [comment]
Firefox 54.0 (32-bit)
Blinking caret in input is not appearing, also no selection highlighting.

<input class="mdl-textfield__input" ng-reflect-pattern=".*" pattern=".*" style="text-align: left;overflow: visible;padding: 2px;" type="text">

In simple <input type='text'></input> caret is acting as expected (blinking + text selection)
