### ISSUE TITLE
[IE11] ShadyDOM breaks template polyfill

### ISSUE THREAD

**Issue by smalluban** [webcomponents/shadydom#71]
In IE11 when ShadyDOM is enabled (tested with `core-js` web api polyfills), `webcomponents/template` polyfill can't define `innerHTML` of nested template, so it set `canDecorate` to false and every next call to `innerHTML` doesn't create proper `<template>` element.

Without ShadyDOM template polyfill works correct.

Example:
```
var inner = '<template><template></template></template>';

var temp1 = document.createElement('template');
temp1.innerHTML = inner;

var temp2 = document.createElement('template');
temp2.innerHTML = inner;

const childTemp = temp2.content.childNodes[0].content.childNodes[0];

console.log(!!childTemp.content); // Should be "true" but is "false"
```

Error that template polyfill catches when try to create `innerHTML` on template:  
![template-error](https://cloud.githubusercontent.com/assets/1906677/22365102/008924dc-e476-11e6-8ac7-d8a0c25386e8.png)

`No such interface supported`

**Comment by sorvell** [comment]
Sorry for the delay on this. This is not an issue when using [webcomponents-lite.js](https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-lite.js).

Would you mind verifying if this is still an issue with your setup and if so, a reproduction would be very helpful. Thanks.

**Comment by smalluban** [comment]
Sorry, i missed notification about your replay. I will try to test it out.

**Comment by smalluban** [comment]
```
IE 11.0.0 (Windows 10 0.0.0): Executed 231 of 231 SUCCESS (5.752 secs / 5.144 secs)
................................................................................
```

Yeah, I can't believe it, that day happened :)
