### ISSUE TITLE
[Safari10] load/error events not triggered from styles in template.content

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadydom#72]
I use a `<template>` to create a `DocumentFragment` out of a string, and append the `DocumentFragment` to the main document asynchronously after creation.
In Safari10 w/ native `<template>` & `shadydom`, the `load/error` events of the nodes contained in `DocumentFragment` are not fired, e.g.
```js
const resource = '<style> body { background-color: green; }<\/style>';
const template = document.createElement('template');
template.innerHTML = resource;
const frag = template.content;

const style = frag.querySelector('style');
// Some manipulation of the style (e.g. append sourceURL).
style.textContent += '\n/*# sourceURL=style.css */\n';
// Listen for load/error.
style.addEventListener('load', function() {
  var success = document.createElement('h2');
  success.textContent = 'loaded!';
  document.body.appendChild(success);
});
style.addEventListener('error', function() {
  var error = document.createElement('h2');
  error.textContent = 'error!';
  document.body.appendChild(error);
});

// Some time later, append the document fragment to the main document
// In Safari10, append after raf or timeout time is too late.
// Promise.resolve().then( // ok
// requestAnimationFrame( // too late
setTimeout( // too late
  () => document.body.appendChild(frag));
```
http://jsbin.com/likego/10/edit?html,output

The events get fired if the fragment is appended after a `Promise.resolve()` time, but not longer than that (e.g. `requestAnimationFrame` or `setTimeout`).

W/o shadydom, events are correctly fired in any of the above cases.

**Comment by sorvell** [comment]
Here's a repro isolated from ShadyDOM: http://jsbin.com/xohomavehu/1/edit?html,console,output.

So far it looks like DOMParser + template is required to trigger the behavior.

**Comment by sorvell** [comment]
It should be possible to avoid the use of DOMParser entirely using a technique like this: http://jsbin.com/viniliv/edit?html,console,output. However, we should file a Webkit issue since this seems like a bug.

**Comment by valdrinkoshi** [comment]
Filed the bug here https://bugs.webkit.org/show_bug.cgi?id=167662

**Comment by bicknellr** [comment]
Is this actually a bug? I wouldn't expect those styles to load if you inserted them into a template's content.

**Comment by valdrinkoshi** [comment]
The bug is that they won't fire load/error events once added to the main document some time later than RAF time

**Comment by bicknellr** [comment]
Why would they necessarily fire before RAF?

**Comment by bicknellr** [comment]
Oh wait, I'm still missing the point of this bug...

**Comment by bicknellr** [comment]
Oh, they're not fired *at all* if you append after the next RAF! Yeah, that's weird.
