### ISSUE TITLE
Tests do not pass

### ISSUE THREAD

**Issue by matthewp** [webcomponents/shadydom#80]
When running tests locally:

```shell
npm test
```

It launches web-component-tester with several failing. I'm not sure if it's because the tests are legitimately failing or because the project expects your local to be set up in a certain way aside from cloning shadydom and running npm install, and then running the tests.

I recommend adding a section to the readme on running tests.

**Comment by sorvell** [comment]
Hmm, we're not able to reproduce the problem. I added a bit of into to the [readme](https://github.com/webcomponents/shadydom/commit/5fbd6fa53a0b842bdf131f345c49f914e866a3ea), but based on the fact that you got web-component-tester running, I don't expect that to help.

Can you give any more info about the failures you're seeing? How many failures in what different browsers? Sorry for the trouble and thanks for the help.

**Comment by matthewp** [comment]
Thanks for adding that to the readme. I was able to get it to work after toggling "Allow Remote Automation" in Safari. I'll close since the tests are actually passing.

One question, it's not clear to me how to run the tests without `npm test`. If you are writing a test I'm assuming you don't run the full test suite every time. How can I run a development server and run one specific test? Thanks again.

**Comment by sorvell** [comment]
Yeah, fair question. To make this easier we run a server that re-directs `../` to `bower_components/`. 

One way to do this is to install the [polymer-cli](https://www.polymer-project.org/1.0/docs/tools/polymer-cli) and then run `polymer serve`. Then you can run the tests in a browser via a url something like `http://127.0.0.1:8081/components/shadydom/tests/test-file.html`
