### ISSUE TITLE
Event patcher doesn't work with EventTargets

### ISSUE THREAD

**Issue by matthewp** [webcomponents/shadydom#81]
If doing something like:

```js
class MyElement extends HTMLElement {
  connectedCallback() {
    this.shadowRoot.querySelector('.something').addEventListener('click', this);
  }

  handleEvent(ev) {

  }
}
```

`this` is the element. The method that should be called is actually `this.handleEvent`.

**Comment by azakus** [comment]
I had to take a hard look at the DOM spec to understand that this is even a feature of the web platform.

Apparently any object with property `handleEvent` can be the second argument to `addEventListener` and `removeEventListener` 😧

**Comment by matthewp** [comment]
This is a pretty prominent feature, I'm surprised you haven't come across it before. The main benefit is not needing to bind your handler function.

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadydom/pull/131.
